# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/icon.ico', 'assets/'),
        ('assets/ffmpeg', 'assets/ffmpeg'),
        ('core', 'core'),
        ('ui', 'ui'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'subprocess',
        'json',
        'os',
        'sys',
        'time',
        'threading',
        'pathlib',
        'urllib.parse',
        'urllib.request',
        'urllib.error',
        're',
        'shutil',
        'psutil',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.models',
        'requests.sessions',
        'requests.structures',
        'requests.utils',
        'urllib3',
        'urllib3.util',
        'urllib3.response',
        'urllib3.connectionpool',
        'urllib3.contrib',
        'urllib3.exceptions',
        'certifi',
        'charset_normalizer',
        'charset_normalizer.md',
        'charset_normalizer.models',
        'charset_normalizer.utils',
        'idna',
        'core',
        'core.utils',
        'core.queue',
        'core.downloader',
        'core.converter',
        'core.first_launch',
        'core.yt_dlp_installer',
        'core.conversion_queue',
        'core.version_manager',
        'ui',
        'ui.sidebar',
        'ui.queue_view',
        'ui.conversion_queue_view',
        'ui.update_dialog',
        # Additional dependencies that might be needed
        'tempfile',
        'dataclasses',
        'enum',
        'typing',
        'concurrent.futures',
        'queue',
        'weakref',
        'contextlib',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
        'sklearn',
        'tensorflow',
        'torch',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Big Gay Downloader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
    version_file=None,
) 