# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('assets/ffmpeg/ffmpeg.exe', 'assets/ffmpeg/'),
    ],
    datas=[
        ('assets/icon.ico', 'assets/'),
        ('core', 'core'),
        ('ui', 'ui'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'customtkinter',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.core_rendering',
        'customtkinter.windows.widgets.font',
        'customtkinter.windows.widgets.image',
        'customtkinter.windows.widgets.scaling',
        'customtkinter.windows.widgets.theme_manager',
        'customtkinter.windows.widgets.appearance_mode',
        'customtkinter.windows.widgets.color',
        'customtkinter.windows.widgets.corner_radius',
        'customtkinter.windows.widgets.hover',
        'customtkinter.windows.widgets.border',
        'customtkinter.windows.widgets.frame',
        'customtkinter.windows.widgets.label',
        'customtkinter.windows.widgets.button',
        'customtkinter.windows.widgets.entry',
        'customtkinter.windows.widgets.switch',
        'customtkinter.windows.widgets.progressbar',
        'customtkinter.windows.widgets.slider',
        'customtkinter.windows.widgets.checkbox',
        'customtkinter.windows.widgets.radiobutton',
        'customtkinter.windows.widgets.optionmenu',
        'customtkinter.windows.widgets.combobox',
        'customtkinter.windows.widgets.scrollable_frame',
        'customtkinter.windows.widgets.tabview',
        'customtkinter.windows.widgets.textbox',
        'customtkinter.windows.widgets.toplevel',
        'customtkinter.windows.widgets.tooltip',
        'customtkinter.windows.widgets.segmented_button',
        'customtkinter.windows.widgets.selectbox',
        'customtkinter.windows.widgets.slider',
        'customtkinter.windows.widgets.spinbox',
        'customtkinter.windows.widgets.treeview',
        'subprocess',
        'json',
        'os',
        'sys',
        'time',
        'threading',
        'pathlib',
        'urllib.parse',
        'urllib.request',
        'urllib.error',
        're',
        'shutil',
        'psutil',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.models',
        'requests.sessions',
        'requests.structures',
        'requests.utils',
        'urllib3',
        'urllib3.util',
        'urllib3.response',
        'urllib3.connectionpool',
        'urllib3.contrib',
        'urllib3.exceptions',
        'certifi',
        'charset_normalizer',
        'charset_normalizer.md',
        'charset_normalizer.models',
        'charset_normalizer.utils',
        'idna',
        'core',
        'core.utils',
        'core.queue',
        'core.downloader',
        'core.converter',
        'core.first_launch',
        'core.yt_dlp_installer',
        'core.conversion_queue',
        'core.version_manager',
        'ui',
        'ui.sidebar',
        'ui.queue_view',
        'ui.conversion_queue_view',
        'ui.update_dialog',
        # Additional dependencies that might be needed
        'tempfile',
        'dataclasses',
        'enum',
        'typing',
        'concurrent.futures',
        'queue',
        'weakref',
        'contextlib',
        'PIL',
        'PIL._tkinter_finder',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'cv2',
        'sklearn',
        'tensorflow',
        'torch',
        'jupyter',
        'IPython',
        'notebook',
        'sphinx',
        'pytest',
        'unittest',
        'doctest',
        'test',
        'tests',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Big Gay Downloader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',  # Use the icon for all icon iterations
    version_file=None,
) 